### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Srinu1331** [sravanapisupati/SampleDataSet#1]
1--Lets take an of 1,2,3,4,5,6,1,7 sum is 7 then
 the o/p he need is (3,4),(6,1),(5,2)

2---If the Given data Looks like
42,34,26
23,56,76
75,17,76,97
22,57,66
Only One Row having One Extra Column how do you Process it

how to solve

**Comment by sravanapisupati** [comment]
Please check below and let me know in case of any issues: 
1) 
val Ab = List(1,2,3,4,5,6,1,7)
     val sum = 7
 
 for(i <- 0 to Ab.length -1){
    
   for (j <- i+1 to Ab.length -1){
     
     if (Ab(i)+Ab(j)==sum)
                print("("+(Ab(i))+" , "+(Ab(j))+")")
   }
 }


2)

 val mySchema = new StructType()
                   .add("col1",IntegerType,true)
                   .add("col2",IntegerType,true)
                   .add("col3",IntegerType,true)
                   .add("col4",IntegerType,true)
                   
    
    val df = spark.read.schema(mySchema).csv("sample_tst.csv").show()

**Comment by Srinu1331** [comment]
Hi

i am getting some questions.if possible please explain with examples.


Question

How to select few columns from an RDD and not converting it to a Data Frame


Question

What is map side join? or How to handle a big table and small table in
hive? which join is useful and how?

Question

Differentiate between Null, Nil, None and Nothing

Question

How to do unit test in Scala?

Questions

How much memory will the spark program consume in the following case:

   a. no of executors - 10
   b. no of cores - 30
   c. Memory is 4GB

Question

 Can we able handle delete records in RDBMS to Hadoop

what optimization u have done in ur projects
DAG vs linage diff

scenarios involved to minimize the shuffle

srini
Thanks & Regards

**Comment by sravanapisupati** [comment]
Hi Friend, all these questions will be answered after the Scala Tutorial videos. Thank you.

**Comment by Srinu1331** [comment]
Thank you for your response.

**Comment by sravanapisupati** [comment]
Scala Tutorials are taking more days then expected. hence thought of posting the quick answers. Please let me know if this is helpful.

1) How to select few columns from an RDD and not converting it to a Data Frame
Ans) You can go thru my youtube videos on - RDD Transformation for detailed scala code - https://www.youtube.com/watch?v=InYqthDjn5I - part1

2) What is map side join? or How to handle a big table and small table in
hive? which join is useful and how?

Ans) When you want to reduce the shuffle between two tables then we use mapside join. For this, we should have at lease one small table and this small table will be cached in the map side. hence the performance will be improved. 

3) Differentiate between Null, Nil, None and Nothing
Ans) NONE - used in Option class in Scala 
     NIL - used for creating empty List
	 Nothing - Is a subtype of every type. If you dot know which type to select and if you leave it, it will take AnyType. If you dont want that, then you give as Nothing type also. 
	 null -  For empty columns, scala considers as null values. It means that the columns are empty in the table. 
	 Null - This is used during the inheritance concepts, usually we dont use much in Scala. 

4) How to do unit test in Scala?

Ans) You can use JUNIT for unit testing in Scala. Its the same way how we use in java. We need to write unit test cases in JUNIT and execute it with different parameters. 

5) How much memory will the spark program consume in the following case:

   a. no of executors - 10
   b. no of cores - 30
   c. Memory is 4GB

Ans) It will be based on the size of the input data and how many shuffle operations you have in the code. If more partitions and more shiffle operation, definitely we need more memory for in-memory operations. 

6)  Can we able handle delete records in RDBMS to Hadoop

Ans) Add a flag for deleted records and them do a full import in SQOOP and then remove the records in HDFS based on this flag. 

7) what optimization u have done in ur projects
Ans) a. using mapPartition instead of map 
     b. caching the RDD or DF wherever required
	 c. unpersist the data once the computation is completed
	 d. use maximum parellelism using repartition/ coleasce
	 e. Try to avoid shuffle operations, if it cant be avoided then try to use optimized functions ( ex.. reducebykey instead of groupby)
	 f. check the memory settings and provide the executors and cores for the spark submit command. 

8) DAG vs linage diff

Ans) On a highlevel note we can say like -> DAG - Physical graph and lineage is logical details of the rdds... first lineage will be created when the compilation happens, and it will try to dag once it is executed. 

9)scenarios involved to minimize the shuffle

Ans) a. use reduce bykey instead of group by key
     b. Broadcast the small table
	 c. use mapPartition instead of map 
	 d. If you need to join multiple tables, first filter and then only perform join 
	 e. dont select entire table data, select required columns.

**Comment by Srinu1331** [comment]
Yes It's helpful.
Thanks for your inputs.
